version: '3.8'

services:
  # Flask application service
  flask:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5001:5000"
    labels:
      - "ca.bdeb.mlops.service=flask"
      - "ca.bdeb.mlops.environment=development"

  # Nginx reverse proxy service
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - flask
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "ca.bdeb.mlops.service=nginx"
      - "ca.bdeb.mlops.environment=development"

#   portainer:
#     image: portainer/portainer-ce:latest
#     container_name: portainer
#     restart: always
#     ports:
#       - "9000:9000"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - portainer_data:/data

# volumes:
#   portainer_data: